"""Entity categories for classification and co-occurrence rules.

Categories group entity types by their nature, enabling:
- Co-occurrence risk scoring (NAME + SSN in same document = high risk)
- Category-based filtering and reporting
- Privacy regulation mapping (HIPAA = health_info, FERPA = education)
"""

from typing import Dict


# --- Entity Categories ---


ENTITY_CATEGORIES: Dict[str, str] = {
    # Direct identifiers
    "SSN": "direct_identifier",
    "PASSPORT": "direct_identifier",
    "DRIVERS_LICENSE": "direct_identifier",
    "STATE_ID": "direct_identifier",
    "TAX_ID": "direct_identifier",
    "AADHAAR": "direct_identifier",
    "AADHAAR_IN": "direct_identifier",
    "A_NUMBER": "direct_identifier",
    "GREEN_CARD_NUMBER": "direct_identifier",
    "VISA_NUMBER": "direct_identifier",
    "I94_NUMBER": "direct_identifier",
    "EAD_NUMBER": "direct_identifier",
    "NATURALIZATION_NUMBER": "direct_identifier",
    "SIN_CA": "direct_identifier",
    "NINO_UK": "direct_identifier",
    "UTR_UK": "direct_identifier",
    "INSEE_FR": "direct_identifier",
    "PERSONALAUSWEIS_DE": "direct_identifier",
    "CODICE_FISCALE_IT": "direct_identifier",
    "DNI_ES": "direct_identifier",
    "CPF_BR": "direct_identifier",
    "RG_BR": "direct_identifier",
    "CURP_MX": "direct_identifier",
    "PAN_IN": "direct_identifier",
    "TFN_AU": "direct_identifier",
    "MY_NRIC": "direct_identifier",
    "CHINA_RESIDENT_ID": "direct_identifier",
    "JAPAN_MY_NUMBER": "direct_identifier",
    "MEDICARE_ID": "direct_identifier",

    # Healthcare / PHI
    "MRN": "health_info",
    "HEALTH_PLAN_ID": "health_info",
    "NPI": "health_info",
    "DEA": "health_info",
    "DIAGNOSIS": "health_info",
    "MEDICATION": "health_info",
    "LAB_TEST": "health_info",
    "ENCOUNTER_ID": "health_info",
    "ACCESSION_ID": "health_info",
    "PHARMACY_ID": "health_info",
    "PATIENT_ACCOUNT": "health_info",
    "DATE_MEDICAL": "health_info",
    "MBI": "health_info",
    "HICN": "health_info",
    "NHS_NUMBER": "health_info",
    "NAME_PATIENT": "health_info",
    "NAME_PROVIDER": "health_info",
    "PAYER": "health_info",
    "ROOM": "health_info",
    "MEDICAL_LICENSE": "health_info",

    # Financial
    "CREDIT_CARD": "financial",
    "BANK_ACCOUNT": "financial",
    "BANK_ROUTING": "financial",
    "IBAN": "financial",
    "SWIFT_BIC": "financial",
    "CUSIP": "financial",
    "ISIN": "financial",
    "SEDOL": "financial",
    "FIGI": "financial",
    "LEI": "financial",
    "BITCOIN_ADDRESS": "financial",
    "ETHEREUM_ADDRESS": "financial",
    "CRYPTO_SEED_PHRASE": "financial",
    "SOLANA_ADDRESS": "financial",
    "CARDANO_ADDRESS": "financial",
    "LITECOIN_ADDRESS": "financial",
    "DOGECOIN_ADDRESS": "financial",
    "XRP_ADDRESS": "financial",
    "MORTGAGE_ACCOUNT": "financial",

    # Contact
    "EMAIL": "contact",
    "PHONE": "contact",
    "ADDRESS": "contact",
    "ZIP": "contact",
    "CITY": "contact",
    "STATE": "contact",
    "LOCATION": "contact",
    "FACILITY": "contact",
    "URL": "contact",

    # Quasi-identifiers
    "NAME": "quasi_identifier",
    "NAME_RELATIVE": "quasi_identifier",
    "DATE_DOB": "quasi_identifier",
    "DOB": "quasi_identifier",
    "DATE": "quasi_identifier",
    "TIME": "quasi_identifier",
    "DATETIME": "quasi_identifier",
    "AGE": "quasi_identifier",
    "GENDER": "quasi_identifier",
    "RACE_ETHNICITY": "quasi_identifier",
    "ETHNICITY": "quasi_identifier",
    "RELIGION": "quasi_identifier",
    "SEXUAL_ORIENTATION": "quasi_identifier",
    "EMPLOYER": "quasi_identifier",
    "PROFESSION": "quasi_identifier",
    "EMPLOYEE_ID": "quasi_identifier",

    # Digital identifiers
    "IP_ADDRESS": "digital_identifier",
    "MAC_ADDRESS": "digital_identifier",
    "DEVICE_ID": "digital_identifier",
    "IMEI": "digital_identifier",
    "USERNAME": "digital_identifier",
    "VIN": "digital_identifier",
    "BIOMETRIC_ID": "digital_identifier",
    "IMAGE_ID": "digital_identifier",
    "TRACKING_NUMBER": "digital_identifier",
    "LICENSE_PLATE": "digital_identifier",
    "IMSI": "digital_identifier",
    "ICCID": "digital_identifier",
    "MSISDN": "digital_identifier",
    "MEID": "digital_identifier",
    "ESN": "digital_identifier",

    # Credentials (all credential types)
    "PASSWORD": "credential",
    "API_KEY": "credential",
    "SECRET": "credential",
    "PRIVATE_KEY": "credential",
    "JWT": "credential",
    "BASIC_AUTH": "credential",
    "BEARER_TOKEN": "credential",
    "DATABASE_URL": "credential",
    "AWS_ACCESS_KEY": "credential",
    "AWS_SECRET_KEY": "credential",
    "AWS_SESSION_TOKEN": "credential",
    "AZURE_STORAGE_KEY": "credential",
    "AZURE_CONNECTION_STRING": "credential",
    "AZURE_SAS_TOKEN": "credential",
    "GOOGLE_API_KEY": "credential",
    "GOOGLE_OAUTH_ID": "credential",
    "GOOGLE_OAUTH_SECRET": "credential",
    "FIREBASE_KEY": "credential",
    "GCP_CREDENTIALS": "credential",
    "GCP_SERVICE_ACCOUNT": "credential",
    "GCP_API_KEY": "credential",
    "DIGITALOCEAN_TOKEN": "credential",
    "LINODE_TOKEN": "credential",
    "VULTR_API_KEY": "credential",
    "ALIBABA_ACCESS_KEY": "credential",
    "ORACLE_CLOUD_KEY": "credential",
    "IBM_CLOUD_KEY": "credential",
    "CLOUDFLARE_API_KEY": "credential",
    "CLOUDFLARE_TOKEN": "credential",
    "OPENAI_API_KEY": "credential",
    "ANTHROPIC_API_KEY": "credential",
    "HUGGINGFACE_TOKEN": "credential",
    "COHERE_API_KEY": "credential",
    "REPLICATE_TOKEN": "credential",
    "STABILITY_API_KEY": "credential",
    "MISTRAL_API_KEY": "credential",
    "TOGETHER_API_KEY": "credential",
    "GROQ_API_KEY": "credential",
    "CIRCLECI_TOKEN": "credential",
    "TRAVIS_TOKEN": "credential",
    "JENKINS_TOKEN": "credential",
    "AZURE_DEVOPS_PAT": "credential",
    "BITBUCKET_TOKEN": "credential",
    "VERCEL_TOKEN": "credential",
    "NETLIFY_TOKEN": "credential",
    "RENDER_API_KEY": "credential",
    "RAILWAY_TOKEN": "credential",
    "FLY_TOKEN": "credential",
    "DOCKER_HUB_TOKEN": "credential",
    "QUAY_TOKEN": "credential",
    "ECR_TOKEN": "credential",
    "GCR_TOKEN": "credential",
    "ACR_TOKEN": "credential",
    "HARBOR_TOKEN": "credential",
    "TELEGRAM_BOT_TOKEN": "credential",
    "TEAMS_WEBHOOK": "credential",
    "ZOOM_JWT": "credential",
    "WEBEX_TOKEN": "credential",
    "TWITCH_TOKEN": "credential",
    "WHATSAPP_TOKEN": "credential",
    "PAYPAL_CLIENT_ID": "credential",
    "PAYPAL_SECRET": "credential",
    "BRAINTREE_TOKEN": "credential",
    "PLAID_CLIENT_ID": "credential",
    "PLAID_SECRET": "credential",
    "ADYEN_API_KEY": "credential",
    "KLARNA_TOKEN": "credential",
    "ATLASSIAN_TOKEN": "credential",
    "NOTION_TOKEN": "credential",
    "AIRTABLE_KEY": "credential",
    "LINEAR_TOKEN": "credential",
    "FIGMA_TOKEN": "credential",
    "ASANA_TOKEN": "credential",
    "MONDAY_TOKEN": "credential",
    "ZENDESK_TOKEN": "credential",
    "INTERCOM_TOKEN": "credential",
    "SEGMENT_KEY": "credential",
    "MIXPANEL_TOKEN": "credential",
    "AMPLITUDE_KEY": "credential",
    "LAUNCHDARKLY_KEY": "credential",
    "SENTRY_DSN": "credential",
    "PAGERDUTY_KEY": "credential",
    "OPSGENIE_KEY": "credential",
    "ROLLBAR_TOKEN": "credential",
    "SUPABASE_KEY": "credential",
    "PLANETSCALE_TOKEN": "credential",
    "NEON_TOKEN": "credential",
    "COCKROACHDB_TOKEN": "credential",
    "SNOWFLAKE_TOKEN": "credential",
    "DATABRICKS_TOKEN": "credential",
    "ELASTICSEARCH_KEY": "credential",
    "ALGOLIA_KEY": "credential",
    "REDIS_URL": "credential",
    "GRAFANA_TOKEN": "credential",
    "POSTMARK_TOKEN": "credential",
    "MAILGUN_KEY": "credential",
    "RESEND_KEY": "credential",
    "SPARKPOST_KEY": "credential",
    "SES_CREDENTIALS": "credential",
    "VONAGE_KEY": "credential",
    "VONAGE_SECRET": "credential",
    "PLIVO_AUTH_ID": "credential",
    "PLIVO_TOKEN": "credential",
    "MESSAGEBIRD_KEY": "credential",
    "BANDWIDTH_TOKEN": "credential",
    "GITHUB_TOKEN": "credential",
    "GITLAB_TOKEN": "credential",
    "SLACK_TOKEN": "credential",
    "SLACK_WEBHOOK": "credential",
    "DISCORD_TOKEN": "credential",
    "DISCORD_WEBHOOK": "credential",
    "STRIPE_KEY": "credential",
    "TWILIO_ACCOUNT_SID": "credential",
    "TWILIO_KEY": "credential",
    "TWILIO_TOKEN": "credential",
    "SENDGRID_KEY": "credential",
    "MAILCHIMP_KEY": "credential",
    "SQUARE_TOKEN": "credential",
    "SQUARE_SECRET": "credential",
    "SHOPIFY_TOKEN": "credential",
    "SHOPIFY_KEY": "credential",
    "SHOPIFY_SECRET": "credential",
    "HEROKU_KEY": "credential",
    "DATADOG_KEY": "credential",
    "NEWRELIC_KEY": "credential",
    "NPM_TOKEN": "credential",
    "PYPI_TOKEN": "credential",
    "NUGET_KEY": "credential",

    # Classification / Government
    "CLASSIFICATION_LEVEL": "classification_marking",
    "CLASSIFICATION_MARKING": "classification_marking",
    "SCI_MARKING": "classification_marking",
    "DISSEMINATION_CONTROL": "classification_marking",
    "CLEARANCE_LEVEL": "classification_marking",
    "ITAR_MARKING": "classification_marking",
    "EAR_MARKING": "classification_marking",
    "CAGE_CODE": "classification_marking",
    "DUNS_NUMBER": "classification_marking",
    "UEI": "classification_marking",
    "DOD_CONTRACT": "classification_marking",
    "GSA_CONTRACT": "classification_marking",

    # Education / FERPA
    "STUDENT_ID": "education",
    "TRANSCRIPT": "education",
    "ENROLLMENT_ID": "education",
    "FINANCIAL_AID_ID": "education",
    "SCHOOL_RECORD": "education",
    "GPA": "education",
    "DISCIPLINARY_RECORD": "education",
    "IEP_ID": "education",
    "TEACHER_ID": "education",
    "FERPA_DIRECTORY_INFO": "education",

    # Legal
    "CASE_NUMBER": "legal",
    "BAR_NUMBER": "legal",
    "COURT_ID": "legal",
    "PACER_ID": "legal",
    "INMATE_NUMBER": "legal",
    "PROBATION_ID": "legal",
    "ARREST_RECORD": "legal",
    "WARRANT_NUMBER": "legal",
    "JUDGMENT_ID": "legal",
    "LEGAL_HOLD_ID": "legal",

    # Vehicle & Transportation
    "REGISTRATION_NUMBER": "vehicle",
    "TITLE_NUMBER": "vehicle",
    "DOT_NUMBER": "vehicle",
    "MC_NUMBER": "vehicle",
    "VESSEL_ID": "vehicle",
    "AIRCRAFT_TAIL": "vehicle",
    "PILOT_LICENSE": "vehicle",
    "CDL_NUMBER": "vehicle",
    "TOLL_ACCOUNT": "vehicle",

    # Immigration
    "SEVIS_ID": "immigration",
    "TRAVEL_DOCUMENT_NUMBER": "immigration",
    "PETITION_NUMBER": "immigration",

    # Insurance
    "POLICY_NUMBER": "insurance",
    "CLAIM_NUMBER": "insurance",
    "AGENT_NUMBER": "insurance",
    "ADJUSTER_ID": "insurance",
    "NAIC_NUMBER": "insurance",
    "AUTO_POLICY_ID": "insurance",
    "HOME_POLICY_ID": "insurance",
    "LIFE_POLICY_ID": "insurance",
    "WORKERS_COMP_CLAIM": "insurance",
    "DISABILITY_CLAIM_ID": "insurance",

    # Real Estate
    "PARCEL_NUMBER": "real_estate",
    "DEED_NUMBER": "real_estate",
    "ESCROW_NUMBER": "real_estate",
    "MLS_NUMBER": "real_estate",
    "HOA_ACCOUNT": "real_estate",
    "TITLE_POLICY_NUMBER": "real_estate",
    "PROPERTY_TAX_ID": "real_estate",

    # Telecommunications
    "CARRIER_ACCOUNT": "telecom",
    "VOIP_ACCOUNT": "telecom",
    "CALLING_CARD_NUMBER": "telecom",
    "PORT_NUMBER": "telecom",

    # Biometric & Genetic
    "FINGERPRINT_TEMPLATE": "biometric",
    "FACE_TEMPLATE": "biometric",
    "IRIS_TEMPLATE": "biometric",
    "VOICE_PRINT": "biometric",
    "RETINAL_SCAN": "biometric",
    "PALM_PRINT": "biometric",
    "GAIT_SIGNATURE": "biometric",
    "DNA_SEQUENCE": "biometric",
    "GENETIC_MARKER": "biometric",
    "ANCESTRY_ID": "biometric",
    "BIOBANK_ID": "biometric",

    # Military
    "EDIPI": "military",
    "SERVICE_NUMBER": "military",
    "MILITARY_ID": "military",
    "VA_CLAIM_NUMBER": "military",
    "DD214_NUMBER": "military",
    "MOS_CODE": "military",
    "UNIT_IDENTIFICATION": "military",
    "SECURITY_BADGE_ID": "military",
    "SIPR_TOKEN": "military",
    "CAC_PIN": "military",

    # Sensitive Files
    "DOTENV_FILE": "sensitive_file",
    "KUBECONFIG": "sensitive_file",
    "SSH_CONFIG": "sensitive_file",
    "DOCKER_CONFIG": "sensitive_file",
    "NPM_RC": "sensitive_file",
    "PYPIRC": "sensitive_file",
    "AWS_CREDENTIALS_FILE": "sensitive_file",
    "NETRC": "sensitive_file",
    "HTPASSWD": "sensitive_file",
    "PGP_PRIVATE": "sensitive_file",
    "TERRAFORM_STATE": "sensitive_file",
    "ANSIBLE_VAULT": "sensitive_file",
    "CERTIFICATE_BUNDLE": "sensitive_file",
    "KEYSTORE": "sensitive_file",
    "WALLET_FILE": "sensitive_file",
    "HISTORY_FILE": "sensitive_file",
    "SHADOW_FILE": "sensitive_file",

    # Misc
    "UNIQUE_ID": "quasi_identifier",
}
