"""Vendor-specific entity type mappings.

Maps vendor-specific entity types from AWS Macie, GCP DLP, Azure Purview,
and other systems to canonical OpenLabels types.

This ensures consistent entity typing regardless of detection source,
enabling unified risk scoring and reporting.
"""

from typing import Dict

# --- Vendor Type Mappings ---
# All vendor-specific types map to canonical OpenLabels types

VENDOR_ALIASES: Dict[str, str] = {
    # ----- AWS Macie -----
    "AWS_CREDENTIALS": "AWS_ACCESS_KEY",
    "OPENSSH_PRIVATE_KEY": "PRIVATE_KEY",
    "PGP_PRIVATE_KEY": "PRIVATE_KEY",
    "PKCS": "PRIVATE_KEY",
    "PUTTY_PRIVATE_KEY": "PRIVATE_KEY",
    "CREDIT_CARD_NUMBER": "CREDIT_CARD",
    "USA_SOCIAL_SECURITY_NUMBER": "SSN",
    "USA_PASSPORT_NUMBER": "PASSPORT",
    "USA_DRIVER_LICENSE": "DRIVERS_LICENSE",
    "BANK_ACCOUNT_NUMBER": "BANK_ACCOUNT",
    "CA_SOCIAL_INSURANCE_NUMBER": "SIN_CA",
    "UK_NATIONAL_INSURANCE_NUMBER": "NINO_UK",
    "DATE_OF_BIRTH": "DOB",
    "EMAIL_ADDRESS": "EMAIL",
    "PHONE_NUMBER": "PHONE",
    "USA_INDIVIDUAL_TAX_IDENTIFICATION_NUMBER": "TAX_ID",
    "USA_MEDICARE_BENEFICIARY_IDENTIFIER": "MBI",
    "USA_HEALTH_INSURANCE_CLAIM_NUMBER": "HICN",
    "USA_NATIONAL_PROVIDER_IDENTIFIER": "NPI",
    "USA_DRUG_ENFORCEMENT_AGENCY_NUMBER": "DEA",
    "VEHICLE_IDENTIFICATION_NUMBER": "VIN",
    "UK_UNIQUE_TAXPAYER_REFERENCE": "UTR_UK",
    "FRANCE_NATIONAL_IDENTIFICATION_NUMBER": "INSEE_FR",
    "GERMANY_NATIONAL_IDENTIFICATION_NUMBER": "PERSONALAUSWEIS_DE",
    "ITALY_NATIONAL_IDENTIFICATION_NUMBER": "CODICE_FISCALE_IT",
    "SPAIN_NATIONAL_IDENTIFICATION_NUMBER": "DNI_ES",
    "BRAZIL_CPF_NUMBER": "CPF_BR",

    # ----- GCP DLP -----
    "US_SOCIAL_SECURITY_NUMBER": "SSN",
    "US_PASSPORT": "PASSPORT",
    "US_DRIVERS_LICENSE_NUMBER": "DRIVERS_LICENSE",
    "US_BANK_ROUTING_MICR": "BANK_ROUTING",
    "US_INDIVIDUAL_TAXPAYER_IDENTIFICATION_NUMBER": "TAX_ID",
    "US_EMPLOYER_IDENTIFICATION_NUMBER": "TAX_ID",
    "US_HEALTHCARE_NPI": "NPI",
    "US_DEA_NUMBER": "DEA",
    "US_MEDICARE_BENEFICIARY_ID_NUMBER": "MBI",
    "US_VEHICLE_IDENTIFICATION_NUMBER": "VIN",
    "CANADA_SOCIAL_INSURANCE_NUMBER": "SIN_CA",
    "UK_TAXPAYER_REFERENCE": "UTR_UK",
    "UK_NATIONAL_HEALTH_SERVICE_NUMBER": "NHS_NUMBER",
    "FRANCE_NIR": "INSEE_FR",
    "GERMANY_IDENTITY_CARD_NUMBER": "PERSONALAUSWEIS_DE",
    "ITALY_FISCAL_CODE": "CODICE_FISCALE_IT",
    "SPAIN_NIE_NUMBER": "DNI_ES",
    "SPAIN_DNI_NUMBER": "DNI_ES",
    "MEXICO_CURP_NUMBER": "CURP_MX",
    "INDIA_AADHAAR_INDIVIDUAL": "AADHAAR_IN",
    "INDIA_PAN_INDIVIDUAL": "PAN_IN",
    "AUSTRALIA_TAX_FILE_NUMBER": "TFN_AU",
    "JAPAN_MY_NUMBER": "JAPAN_MY_NUMBER",
    "CHINA_RESIDENT_ID_NUMBER": "CHINA_RESIDENT_ID",
    "IBAN_CODE": "IBAN",
    "SWIFT_CODE": "SWIFT_BIC",
    "PERSON_NAME": "NAME",
    "STREET_ADDRESS": "ADDRESS",
    "JSON_WEB_TOKEN": "JWT",
    "HTTP_COOKIE": "SECRET",
    "XSRF_TOKEN": "SECRET",
    "AUTH_TOKEN": "BEARER_TOKEN",
    "ENCRYPTION_KEY": "SECRET",
    "IMEI_HARDWARE_ID": "IMEI",
    "ETHNIC_GROUP": "ETHNICITY",

    # ----- Azure Purview -----
    "U.S. Social Security Number (SSN)": "SSN",
    "U.S. / U.K. Passport Number": "PASSPORT",
    "U.S. Driver's License Number": "DRIVERS_LICENSE",
    "U.S. Bank Account Number": "BANK_ACCOUNT",
    "U.S. Individual Taxpayer Identification Number (ITIN)": "TAX_ID",
    "Credit Card Number": "CREDIT_CARD",
    "International Banking Account Number (IBAN)": "IBAN",
    "SWIFT Code": "SWIFT_BIC",
    "Canada Social Insurance Number": "SIN_CA",
    "U.K. National Insurance Number (NINO)": "NINO_UK",
    "U.K. National Health Service Number": "NHS_NUMBER",
    "France National ID Card (CNI)": "INSEE_FR",
    "France Social Security Number (INSEE)": "INSEE_FR",
    "Germany Identity Card Number": "PERSONALAUSWEIS_DE",
    "Germany Tax Identification Number": "PERSONALAUSWEIS_DE",
    "Italy Fiscal Code": "CODICE_FISCALE_IT",
    "Spain DNI": "DNI_ES",
    "Spain Social Security Number": "DNI_ES",
    "Brazil CPF Number": "CPF_BR",
    "Brazil National ID Card (RG)": "RG_BR",
    "Mexico CURP": "CURP_MX",
    "India Permanent Account Number (PAN)": "PAN_IN",
    "India Unique Identification (Aadhaar) Number": "AADHAAR_IN",
    "Australia Tax File Number": "TFN_AU",
    "Japan My Number - Personal": "JAPAN_MY_NUMBER",
    "China Resident Identity Card Number": "CHINA_RESIDENT_ID",
    "Malaysia Identity Card Number": "MY_NRIC",
    "Email": "EMAIL",
    "Phone Number": "PHONE",
    "Person's Name": "NAME",
    "Address": "ADDRESS",
    "Date of Birth": "DOB",
    "Azure Storage Account Key": "AZURE_STORAGE_KEY",
    "Azure SQL Connection String": "AZURE_CONNECTION_STRING",
    "Azure Service Bus Connection String": "AZURE_CONNECTION_STRING",
    "Azure IoT Connection String": "AZURE_CONNECTION_STRING",
    "Azure Cosmos DB Connection String": "AZURE_CONNECTION_STRING",
    "Azure Redis Cache Connection String": "AZURE_CONNECTION_STRING",
    "Azure SAS Token": "AZURE_SAS_TOKEN",
    "Azure AD Client Secret": "SECRET",
    "General Password": "PASSWORD",
    "IP Address": "IP_ADDRESS",
    "IPv4 Address": "IP_ADDRESS",
    "IPv6 Address": "IP_ADDRESS",
    "MAC Address": "MAC_ADDRESS",

    # ----- OpenLabels Scanner -----
    # Scanner outputs short names, map to canonical with country codes
    "SIN": "SIN_CA",
    "TFN": "TFN_AU",
    "NINO": "NINO_UK",
    "DRIVER_LICENSE": "DRIVERS_LICENSE",
    "DRIVERS LICENSE": "DRIVERS_LICENSE",
    "DL": "DRIVERS_LICENSE",
    "ID_NUMBER": "STATE_ID",
    "NATIONAL_ID": "STATE_ID",
    "AADHAAR": "AADHAAR_IN",
    "PAN": "PAN_IN",
    "CURP": "CURP_MX",
    "CPF": "CPF_BR",
    "RG": "RG_BR",
    "DNI": "DNI_ES",
    "NIE": "DNI_ES",
    "NIF": "DNI_ES",
    "INSEE": "INSEE_FR",
    "MY_NUMBER": "JAPAN_MY_NUMBER",
    "CHINA_ID": "CHINA_RESIDENT_ID",
    "RESIDENT_ID": "CHINA_RESIDENT_ID",
}
